spring.application.name=Voxa
spring.datasource.url=jdbc:mysql://localhost:3306/voxa_db?createDatabaseIfNotExist=true
spring.datasource.username=Jonathan
spring.datasource.password=9193jojo
spring.jpa.hibernate.ddl-auto=update
